/**
 * Everything a crawler reads before it has run a line of JavaScript.
 *
 * Facebook, X, LinkedIn, WhatsApp, iMessage and Slack all fetch the raw HTML
 * and never execute the bundle, so the `<Helmet>` block in `App.tsx` is
 * invisible to every one of them. The tags that decide what a shared link
 * looks like therefore have to be in `index.html` at build time — this module
 * is where their contents come from, and `pawtxSeo()` in `vite.config.ts`
 * substitutes them in.
 *
 * Imported by the Vite config, so it must stay free of `import.meta.env`,
 * `window` and anything else that only exists in the browser.
 */
import { ORG_EMAIL, ORG_LINKS, ORG_POSTAL_ADDRESS } from '../data/orgLinks';

/** Where the built site is published. Also the Vite `base` — see the config. */
export const SITE_PATH = '/';

// The custom domain in `public/CNAME`. GitHub Pages serves the site there and
// redirects the old erohaj.github.io/peace-academy-of-west-texas/ address to
// it, so nothing that was ever shared stops working.
const SITE_ORIGIN = 'https://new.pawtx.org';

/**
 * Absolute, production URL of the home page.
 *
 * Deliberately a constant rather than something derived from the current
 * origin: `og:image` and `canonical` are read by a crawler on someone else's
 * server, where a relative URL resolves to nothing and a localhost URL
 * resolves to their localhost. It stays the production address even in a dev
 * build for the same reason.
 *
 * Not to be confused with `getSiteUrl()` in `supabaseClient.ts`, which is the
 * *runtime* origin used for auth redirects and has to be localhost in dev.
 *
 * If the site moves to the organisation's own domain, this and `SITE_PATH` are
 * the only two values to change.
 */
export const CANONICAL_URL = `${SITE_ORIGIN}${SITE_PATH}`;

export const SITE_NAME = 'Peace Academy of West Texas';

/** Also the home tab's title in `App.tsx`, so the two cannot disagree. */
export const SITE_TITLE = `${SITE_NAME} | Engaging Minds, Building Community`;

export const SITE_DESCRIPTION =
  'Promoting cross-cultural education, interfaith dialogue, and food security in Midland & Odessa, Texas.';

/** 1200x630 share card, generated by `npm run seo:assets`. */
export const OG_IMAGE_URL = `${CANONICAL_URL}og-image.jpg`;

export const OG_IMAGE_ALT =
  'Children and families carrying flags from around the world in a parade at a Peace Academy of West Texas festival';

/** Brand parchment, so the mobile browser chrome blends into the page. */
export const THEME_COLOR = '#FDFBF7';

/**
 * `@paowtx`, which X prints on the share card as the account it credits.
 * Derived from the profile link so the two cannot drift — and note the handle
 * differs from the Facebook/YouTube one, which is `pawtx`.
 */
export const X_HANDLE = `@${new URL(ORG_LINKS.x).pathname.replace(/\//g, '')}`;

/**
 * Structured data describing the organisation itself.
 *
 * `sameAs` is the part search engines actually use — it is how they tie this
 * site to the Instagram, Facebook, YouTube and X accounts and treat them as
 * one organisation. It lists identity-confirming profiles only: the Taplink
 * link-in-bio page and the Google Maps pin are navigation aids, not proof of
 * who this is.
 */
export const organizationJsonLd = () => ({
  '@context': 'https://schema.org',
  // Both apply, and schema.org allows an item to carry more than one type.
  '@type': ['NGO', 'EducationalOrganization'],
  name: SITE_NAME,
  alternateName: 'PAWTX',
  url: CANONICAL_URL,
  logo: `${CANONICAL_URL}icon-512.png`,
  image: OG_IMAGE_URL,
  description: SITE_DESCRIPTION,
  email: ORG_EMAIL,
  // As published on the site's own masthead: "501(c)(3) Non-Profit • West
  // Texas Since 2018".
  foundingDate: '2018',
  nonprofitStatus: 'Nonprofit501c3',
  address: {
    '@type': 'PostalAddress',
    ...ORG_POSTAL_ADDRESS
  },
  areaServed: [
    { '@type': 'City', name: 'Odessa' },
    { '@type': 'City', name: 'Midland' }
  ],
  sameAs: [
    ORG_LINKS.instagram,
    ORG_LINKS.facebook,
    ORG_LINKS.youtube,
    ORG_LINKS.x,
    ORG_LINKS.website
  ]
});

/**
 * Crawlers only honour robots.txt at the root of an origin. Now that the site
 * has its own domain this file lands at that root and is actually read — on
 * the old GitHub Pages sub-path it never was, because `erohaj.github.io/
 * robots.txt` belongs to whatever repo serves that user's root site. Nothing
 * here is blocked either way, so the change costs nothing to get wrong.
 */
export const robotsTxt = () =>
  ['User-agent: *', 'Disallow:', '', `Sitemap: ${CANONICAL_URL}sitemap.xml`, ''].join('\n');

/**
 * One entry, because the site is one URL: navigation is a tab in the Zustand
 * store, not a route, so there is no second page to list.
 */
export const sitemapXml = (lastModified: Date) =>
  [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    '  <url>',
    `    <loc>${CANONICAL_URL}</loc>`,
    `    <lastmod>${lastModified.toISOString().slice(0, 10)}</lastmod>`,
    '  </url>',
    '</urlset>',
    ''
  ].join('\n');
