-- Generated by scripts/generate-legal-seed.mjs from legal/*.md. Do not hand-edit —
-- regenerate instead, or this file and the drafts it came from will drift apart.
--
-- Idempotent: upserts by slug/version, safe to paste into the SQL editor twice.
--
-- The English body still carries "Draft — not for use until reviewed by a
-- Texas-licensed attorney" on purpose. It is the guardrail that stops this
-- from being put in front of a real volunteer or a real parent before that
-- review has happened — see legal/README.md. Remove that sentence from the
-- markdown (and regenerate) only once counsel has signed off.

-- ---------------------------------------------------------------------------
-- volunteer-application
-- ---------------------------------------------------------------------------

insert into public.legal_documents (slug, title, title_es, kind, required, minors_only, sort_order)
values ($doc$volunteer-application$doc$, $doc$Volunteer Application$doc$, $doc$Solicitud de Voluntariado$doc$, $doc$application$doc$, true, false, 10)
on conflict (slug) do update set
  title = excluded.title, title_es = excluded.title_es, kind = excluded.kind,
  minors_only = excluded.minors_only, sort_order = excluded.sort_order;

with doc as (
  select id from public.legal_documents where slug = $doc$volunteer-application$doc$
)
insert into public.legal_document_versions (document_id, version, effective_from, body_md, body_md_es, is_current)
select doc.id, '1.0', current_date,
  $doc$**Peace Academy of West Texas** — 3411 Brentwood Drive, Odessa, Texas 79762.

> **Draft — not for use until reviewed by a Texas-licensed attorney.**
>
> This is the field specification for the application form, and the notices
> that must appear on it. The fields map to `public.volunteer_applications`.

---

## Notice shown at the top of the form

> We ask for this information to place you in a role that suits you, to reach
> you about shifts, and to contact someone on your behalf if you are hurt while
> volunteering. **We do not sell it, and we do not share it outside Peace
> Academy of West Texas** except where the law requires.
>
> Applying does not commit you to anything. Nothing is scheduled until you
> choose a shift.

## Fields

### About you

| Field | Required | Notes |
|---|---|---|
| Full legal name | yes | As it should appear on a certificate of service |
| Email | yes | Also the sign-in address |
| Phone | no | |
| Date of birth | yes | Determines whether guardian consent is required. **Not** used for eligibility beyond that |
| Street address, city, state, ZIP | no | Asked because some grant reporting is by county |
| Preferred language | no | English / Spanish / other |

**Minimum age for self-registration is 13.** Someone younger is enrolled by a
parent, who completes the form on their behalf. This keeps the portal clear of
the verifiable-parental-consent obligations that COPPA attaches to collecting
personal information online from a child under 13.

### Emergency contact

| Field | Required |
|---|---|
| Name | yes |
| Phone | yes |
| Relationship to you | no |

Stated on the form: *"We will only use this if you are hurt or taken ill while
volunteering and we cannot reach you."*

### What you would like to do

| Field | Required | Notes |
|---|---|---|
| Areas of interest | no | Multi-select from the six volunteer roles |
| Skills and experience | no | Free text — languages spoken, food handling, first aid, driving, trades |
| Availability | no | Free text or day/time grid |
| Interested in youth programmes | no | Checkbox. **Screening applies before any unsupervised contact with minors — see the note below** |
| Why you would like to volunteer | no | Free text |

### What is deliberately not asked

- **Criminal history.** Not on the general application. Screening, where it is
  required, is a separate step with its own authorisation and its own FCRA
  obligations if a consumer reporting agency is used. Asking everyone on the
  first form is both unnecessary and a legal exposure of its own.
- **Immigration or citizenship status.** Irrelevant to volunteering and not the
  Organization's business.
- **Health conditions.** Only what someone chooses to disclose so their role can
  be made safe. Do not ask for a medical history.
- **Social security number.** Never, for a volunteer.

## Notice shown above the submit button

> Submitting this application does not make you a volunteer. We will review it
> and get in touch. Before your first shift you will be asked to read and sign
> the Volunteer Agreement, the Release and Waiver, and the Code of Conduct.
> Photo consent is separate, and optional.

## After submission

Status moves through `submitted → in_review → approved | declined`. A volunteer
may withdraw at any time (`withdrawn`).

Retention: **to be set by the attorney.** Applications, dates of birth and
emergency contacts should not be kept indefinitely, and nothing in the schema
purges them today.$doc$,
  $doc$[Spanish translation pending attorney-reviewed English text. Contact paowtx@gmail.com for this document in Spanish.]$doc$,
  true
from doc
on conflict (document_id, version) do update set
  body_md = excluded.body_md, body_md_es = excluded.body_md_es, is_current = true;

-- ---------------------------------------------------------------------------
-- volunteer-agreement
-- ---------------------------------------------------------------------------

insert into public.legal_documents (slug, title, title_es, kind, required, minors_only, sort_order)
values ($doc$volunteer-agreement$doc$, $doc$Volunteer Agreement$doc$, $doc$Acuerdo de Voluntariado$doc$, $doc$agreement$doc$, true, false, 20)
on conflict (slug) do update set
  title = excluded.title, title_es = excluded.title_es, kind = excluded.kind,
  minors_only = excluded.minors_only, sort_order = excluded.sort_order;

with doc as (
  select id from public.legal_documents where slug = $doc$volunteer-agreement$doc$
)
insert into public.legal_document_versions (document_id, version, effective_from, body_md, body_md_es, is_current)
select doc.id, '1.0', current_date,
  $doc$**Peace Academy of West Texas** — 3411 Brentwood Drive, Odessa, Texas 79762.

> **Draft — not for use until reviewed by a Texas-licensed attorney.**

This agreement sets out what the Organization asks of its volunteers and what
volunteers can expect in return. It is not an employment contract.

---

## 1. Volunteer status

I am serving as a volunteer. I understand and agree that:

- **I am not an employee** of the Organization, and this agreement creates no
  employment relationship, no contract of employment, and no expectation of
  continued service.
- **I serve without compensation.** I am not entitled to wages, salary, stipend,
  or any other payment for my time, and I am not volunteering in the expectation
  of future paid work.
- I am not covered by the Organization's workers' compensation insurance (if
  any), nor by health, disability or accident insurance provided by it.
- Volunteer work will not displace a paid employee or duplicate work the
  Organization pays someone else to do.

The Organization may reimburse pre-approved out-of-pocket expenses. Any
reimbursement requires a receipt and prior approval, and is a reimbursement of
cost rather than payment for time.

## 2. What the Organization commits to

- To tell me what a role involves before I take it on, and to provide the
  orientation and training that role needs.
- To provide a named supervisor for each activity and a way to reach them.
- To treat me with respect, and to apply its non-discrimination and
  anti-harassment commitments to volunteers as it does to staff.
- To keep the personal information I provide confidential, and to use it only to
  run its volunteer programme.
- To keep an accurate record of the hours I serve, and to provide a certificate
  of service on request.

## 3. What I commit to

- To arrive when I have said I will, and to give as much notice as I can when I
  cannot — a shift left unfilled is usually a service that does not happen.
- To follow the Code of Conduct (`06-code-of-conduct.md`), which I have read.
- To follow the reasonable instructions of my supervisor, and safety rules in
  particular.
- To work within the role I have been given, and to ask before doing anything
  outside it. I will not represent myself as speaking for the Organization, or
  make commitments on its behalf, without written authorisation.
- To report accidents, injuries, near-misses and property damage to my
  supervisor **the same day**.
- Not to volunteer while under the influence of alcohol or of any drug that
  impairs my ability to serve safely.

## 4. Confidentiality

In the course of volunteering I may learn personal information about
programme participants, donors, other volunteers, or families receiving
assistance. **I will not disclose it to anyone outside the Organization, and I
will not use it for any purpose of my own.** This obligation continues after I
stop volunteering. If I am unsure whether something is confidential, I will
treat it as if it is and ask my supervisor.

## 5. Hours and records

Hours are credited by staff after an activity, on the basis of attendance
actually observed. Signing up for a shift is not the same as serving it. I may
view my recorded hours at any time in the volunteer portal, and I will raise any
discrepancy promptly, while it can still be checked.

## 6. Media

Photography and video consent is given separately, in `04-media-consent.md`. It
is optional, and declining it does not affect my ability to volunteer.

## 7. Ending the arrangement

Either of us may end this arrangement at any time, with or without reason and
without notice. The Organization may also suspend or remove me from an activity
immediately where it believes there is a risk to a participant, another
volunteer, or the Organization. Sections 4 (Confidentiality) and any obligation
under `03-release-and-waiver.md` survive.

## 8. Equal opportunity

The Organization welcomes volunteers without regard to race, colour, national
origin, ancestry, religion, sex, sexual orientation, gender identity, age,
disability, veteran status, or any other characteristic protected by law. I may
ask for a reasonable accommodation at any time by writing to paowtx@gmail.com,
and doing so will not count against me.

## 9. General

This agreement is governed by Texas law. It replaces any prior understanding
about my volunteer service. If any part is unenforceable, the rest stands.$doc$,
  $doc$[Spanish translation pending attorney-reviewed English text. Contact paowtx@gmail.com for this document in Spanish.]$doc$,
  true
from doc
on conflict (document_id, version) do update set
  body_md = excluded.body_md, body_md_es = excluded.body_md_es, is_current = true;

-- ---------------------------------------------------------------------------
-- release-and-waiver
-- ---------------------------------------------------------------------------

insert into public.legal_documents (slug, title, title_es, kind, required, minors_only, sort_order)
values ($doc$release-and-waiver$doc$, $doc$Release, Waiver of Liability, and Assumption of Risk$doc$, $doc$Exención de Responsabilidad y Aceptación de Riesgos$doc$, $doc$release$doc$, true, false, 30)
on conflict (slug) do update set
  title = excluded.title, title_es = excluded.title_es, kind = excluded.kind,
  minors_only = excluded.minors_only, sort_order = excluded.sort_order;

with doc as (
  select id from public.legal_documents where slug = $doc$release-and-waiver$doc$
)
insert into public.legal_document_versions (document_id, version, effective_from, body_md, body_md_es, is_current)
select doc.id, '1.0', current_date,
  $doc$**Peace Academy of West Texas** — a Texas non-profit corporation, 3411 Brentwood
Drive, Odessa, Texas 79762 (the "Organization").

> **Draft — not for use until reviewed by a Texas-licensed attorney.** See
> `legal/README.md`. If the signer is under 18, this document is signed by the
> volunteer *and* by a parent or guardian under `05-guardian-consent.md`, and
> the limits described there apply.

**Read this before signing. It affects your legal rights.**

---

## 1. Activities covered

I am volunteering with the Organization. My activities may include, without
limitation: preparing and serving food; setting up, running and dismantling
events indoors and outdoors; lifting and carrying supplies; assembling and
distributing relief packages; greeting and assisting the public; interpreting
and translating; supporting youth and sports programming; and travelling
between sites (together, the "Activities").

## 2. Assumption of risk

I understand that the Activities carry risks that cannot be eliminated, however
carefully the Organization conducts them. These include, without limitation:
slips, trips and falls; cuts, burns and injuries from kitchen equipment and hand
tools; strains and crush injuries from lifting or moving heavy objects; heat
exhaustion, heat stroke, sunburn and dehydration during outdoor events in West
Texas; allergic reactions, including to foods and cleaning products;
communicable illness; injury caused by other volunteers, participants, members
of the public, or animals; property damage or loss; and the risks of travelling
to and from sites, including motor vehicle collisions.

I understand this list is not complete, and that there may be risks not now
foreseeable. **I knowingly and voluntarily accept these risks** and choose to
participate anyway.

## 3. Fitness and medical care

I represent that I am physically able to perform the Activities I take on, and
that I will tell my supervisor about any condition, allergy, or limitation that
could affect my safety or anyone else's. I authorise the Organization to obtain
emergency medical care for me if I am unable to consent, and I accept financial
responsibility for that care. I understand **the Organization does not provide
health, medical, disability or workers' compensation insurance for volunteers**
and that I am responsible for my own coverage.

## 4. Release of claims

> ### ⚠ READ THIS PARAGRAPH CAREFULLY. IT RELEASES CLAIMS FOR THE ORGANIZATION'S OWN NEGLIGENCE.
>
> **IN EXCHANGE FOR BEING PERMITTED TO VOLUNTEER, I RELEASE, WAIVE AND DISCHARGE
> PEACE ACADEMY OF WEST TEXAS, ITS DIRECTORS, OFFICERS, EMPLOYEES, AGENTS,
> VOLUNTEERS AND PROPERTY OWNERS WHOSE PREMISES ARE USED (THE "RELEASED
> PARTIES") FROM ALL LIABILITY, CLAIMS, DEMANDS AND CAUSES OF ACTION FOR ANY
> INJURY, DEATH, ILLNESS, OR LOSS OF OR DAMAGE TO PROPERTY THAT I SUFFER
> ARISING OUT OF THE ACTIVITIES — INCLUDING ANY SUCH INJURY, DEATH, ILLNESS,
> LOSS OR DAMAGE CAUSED IN WHOLE OR IN PART BY THE ORDINARY NEGLIGENCE OF ANY
> OF THE RELEASED PARTIES.**
>
> **I UNDERSTAND THAT I AM GIVING UP SUBSTANTIAL RIGHTS, INCLUDING MY RIGHT TO
> SUE THE RELEASED PARTIES FOR THEIR OWN NEGLIGENCE.**

This release does **not** apply to gross negligence, wilful or wanton
misconduct, intentional wrongdoing, or any liability that Texas law does not
permit to be released.

## 5. Indemnity

I agree to indemnify and hold the Released Parties harmless from any claim
brought by a third party arising out of my own negligent or wrongful act or
omission during the Activities. This does not require me to indemnify a
Released Party against that party's own negligence.

## 6. Statutory protections preserved

Nothing in this document waives or limits any protection available to the
Organization or to volunteers under the Texas Charitable Immunity and Liability
Act (Tex. Civ. Prac. & Rem. Code ch. 84) or the federal Volunteer Protection
Act of 1997 (42 U.S.C. §14501 et seq.).

## 7. General

This document is governed by the laws of the State of Texas, without regard to
conflict-of-laws rules. Venue for any dispute lies in Ector County, Texas. If
any part is held unenforceable, the rest remains in force, and the
unenforceable part is to be given the narrowest reading that is enforceable.
This release binds my heirs, personal representatives and assigns.

I have read this document in full. **I understand it is a release of liability
and a contract, and I sign it freely.** No one has told me it is merely a
formality.$doc$,
  $doc$[Spanish translation pending attorney-reviewed English text. Contact paowtx@gmail.com for this document in Spanish.]$doc$,
  true
from doc
on conflict (document_id, version) do update set
  body_md = excluded.body_md, body_md_es = excluded.body_md_es, is_current = true;

-- ---------------------------------------------------------------------------
-- media-consent
-- ---------------------------------------------------------------------------

insert into public.legal_documents (slug, title, title_es, kind, required, minors_only, sort_order)
values ($doc$media-consent$doc$, $doc$Photo and Media Consent$doc$, $doc$Consentimiento de Fotografía y Medios$doc$, $doc$media_consent$doc$, true, false, 40)
on conflict (slug) do update set
  title = excluded.title, title_es = excluded.title_es, kind = excluded.kind,
  minors_only = excluded.minors_only, sort_order = excluded.sort_order;

with doc as (
  select id from public.legal_documents where slug = $doc$media-consent$doc$
)
insert into public.legal_document_versions (document_id, version, effective_from, body_md, body_md_es, is_current)
select doc.id, '1.0', current_date,
  $doc$**Peace Academy of West Texas** — 3411 Brentwood Drive, Odessa, Texas 79762.

> **Draft — not for use until reviewed by a Texas-licensed attorney.**
>
> **This consent is optional.** Declining it must not affect anyone's ability to
> volunteer or to take part in a programme, and the onboarding flow is built so
> that "no" is a normal outcome rather than a blocked path.

---

## 1. What is being asked

The Organization photographs and films its events — cooking classes, cultural
festivals, relief drives, seminars — and uses the results to show what it does
and to raise support. This form asks whether your image may be included.

## 2. What you are consenting to, if you say yes

Permission for the Organization to record my image, likeness, voice and first
name at its activities, and to reproduce, publish and distribute those
recordings:

- on the PAWTX website and its social media accounts;
- in printed material such as brochures, flyers, newsletters and annual reports;
- in grant applications and reports to funders;
- in local press coverage of PAWTX activities.

This permission is granted worldwide, without a time limit except as described
in section 5, and without payment. I understand the Organization may crop, edit
or caption the material, and I waive any right to inspect or approve a
particular use in advance.

## 3. What is not being asked for

The Organization will **not**:

- publish my surname, address, telephone number or email alongside my image;
- publish my image in a way that suggests I endorse a commercial product, a
  political candidate, or a religious position;
- sell or license my image to a third party for their own advertising;
- publish an image of a minor without the consent recorded under
  `05-guardian-consent.md`.

## 4. Choose one

- ☐ **Yes** — I consent as described above.
- ☐ **Photographs only** — I consent to still photography but not to video or
  audio recording.
- ☐ **No** — I do not consent. Please do not include me in photographs or
  recordings intended for publication.

If you choose "No", tell the person with the camera at an event as well.
Consent recorded here is honoured by staff, but a volunteer photographer at a
crowded festival cannot check a list in the moment.

## 5. Withdrawing consent

I may withdraw this consent at any time by writing to **paowtx@gmail.com**.

**Withdrawal applies going forward.** On withdrawal the Organization will,
within 30 days, stop using my image in new material and remove it from the
website and from social media accounts it controls where it can reasonably be
identified. It **cannot** recall material already printed and distributed, or
copies already shared or reposted by others, and it does not undertake to do
so. Archived material held for the Organization's own records may be retained.

## 6. Minors

Where the person recorded is under 18, this consent has no effect unless a
parent or guardian has signed `05-guardian-consent.md`. **For minors the
default is no.**$doc$,
  $doc$[Spanish translation pending attorney-reviewed English text. Contact paowtx@gmail.com for this document in Spanish.]$doc$,
  true
from doc
on conflict (document_id, version) do update set
  body_md = excluded.body_md, body_md_es = excluded.body_md_es, is_current = true;

-- ---------------------------------------------------------------------------
-- guardian-consent
-- ---------------------------------------------------------------------------

insert into public.legal_documents (slug, title, title_es, kind, required, minors_only, sort_order)
values ($doc$guardian-consent$doc$, $doc$Parent / Guardian Consent for a Volunteer Under 18$doc$, $doc$Consentimiento de Padre/Tutor para un Voluntario Menor de 18$doc$, $doc$guardian_consent$doc$, true, true, 50)
on conflict (slug) do update set
  title = excluded.title, title_es = excluded.title_es, kind = excluded.kind,
  minors_only = excluded.minors_only, sort_order = excluded.sort_order;

with doc as (
  select id from public.legal_documents where slug = $doc$guardian-consent$doc$
)
insert into public.legal_document_versions (document_id, version, effective_from, body_md, body_md_es, is_current)
select doc.id, '1.0', current_date,
  $doc$**Peace Academy of West Texas** — 3411 Brentwood Drive, Odessa, Texas 79762.

> **Draft — not for use until reviewed by a Texas-licensed attorney.**
>
> **Read this note before adapting the document.** It is deliberately *not*
> drafted as a waiver of the minor's claims. Under *Munoz v. II Jaz Inc.*,
> 863 S.W.2d 207 (Tex. App.—Houston [14th Dist.] 1993), a parent's authority
> over a child does not extend to releasing the child's own cause of action,
> and a clause purporting to do so is very likely unenforceable in Texas.
>
> Adding one would not make the Organization safer. It would add a clause a
> court strikes, and invite the argument that the document as a whole was
> written to overreach. What protects minors here is insurance, supervision
> and screening — not paperwork. See `legal/README.md`.

---

I am the parent or legal guardian of the minor named below (the "Minor"), and I
have the legal authority to make this decision for them.

## 1. Consent to participate

I consent to the Minor volunteering with the Organization and taking part in its
activities, which may include preparing and serving food, setting up and running
indoor and outdoor events, assembling and distributing relief packages,
assisting the public, and supporting youth and sports programming.

I understand the Minor will be supervised by Organization staff or approved
adult volunteers, and I have discussed the Code of Conduct
(`06-code-of-conduct.md`) with them.

## 2. Acknowledgement of risk

I have read the description of risks in the Release and Waiver
(`03-release-and-waiver.md`) and I understand them. They include, among others,
injuries from kitchen equipment and hand tools, lifting injuries, heat illness
during outdoor events in West Texas, allergic reactions, communicable illness,
and injury caused by other people present.

**I accept that these risks exist and I consent to the Minor's participation
with that understanding.**

## 3. Transportation

Please indicate one:

- ☐ The Minor will be brought to and collected from activities by me or by an
  adult I authorise.
- ☐ I authorise the Organization to transport the Minor in a vehicle driven by
  a screened adult volunteer or staff member.
- ☐ I authorise the Minor to travel to and from activities independently.

## 4. Emergency medical authorisation

If the Minor is injured or becomes ill and I cannot be reached in time, I
authorise the Organization to seek emergency medical treatment for them,
including transport by ambulance. I accept financial responsibility for that
treatment. I understand **the Organization does not provide medical or accident
insurance for volunteers.**

- Known allergies, conditions, or medications: `_______________`
- Health insurance carrier and policy number (optional): `_______________`

## 5. Release of my own claims, and indemnity

**This section releases my own claims. It does not release, and does not
purport to release, any claim belonging to the Minor.**

To the extent permitted by Texas law, I release the Organization, its
directors, officers, employees, agents and volunteers from claims **that I
personally** may have arising out of the Minor's participation, including
claims for my own loss of the Minor's services or companionship and for
expenses I incur — **including where such a claim arises in whole or in part
from the ordinary negligence of the Organization.** This does not extend to
gross negligence, wilful or wanton misconduct, or intentional wrongdoing.

I agree to indemnify the Organization against claims brought by a third party
arising from the Minor's own wrongful act.

## 6. Media

Consent to photography and video of the Minor is given separately, in
`04-media-consent.md`, and may be declined without affecting the Minor's ability
to volunteer. **Consent for a minor is off by default and requires this
signature.**

## 7. Communication

The Organization will send scheduling messages to me as well as to the Minor. I
may withdraw this consent at any time by writing to paowtx@gmail.com, which
also withdraws the Minor from future activities.$doc$,
  $doc$[Spanish translation pending attorney-reviewed English text. Contact paowtx@gmail.com for this document in Spanish.]$doc$,
  true
from doc
on conflict (document_id, version) do update set
  body_md = excluded.body_md, body_md_es = excluded.body_md_es, is_current = true;

-- ---------------------------------------------------------------------------
-- code-of-conduct
-- ---------------------------------------------------------------------------

insert into public.legal_documents (slug, title, title_es, kind, required, minors_only, sort_order)
values ($doc$code-of-conduct$doc$, $doc$Volunteer Code of Conduct$doc$, $doc$Código de Conducta del Voluntario$doc$, $doc$code_of_conduct$doc$, true, false, 60)
on conflict (slug) do update set
  title = excluded.title, title_es = excluded.title_es, kind = excluded.kind,
  minors_only = excluded.minors_only, sort_order = excluded.sort_order;

with doc as (
  select id from public.legal_documents where slug = $doc$code-of-conduct$doc$
)
insert into public.legal_document_versions (document_id, version, effective_from, body_md, body_md_es, is_current)
select doc.id, '1.0', current_date,
  $doc$**Peace Academy of West Texas** — 3411 Brentwood Drive, Odessa, Texas 79762.

> **Draft — not for use until reviewed by a Texas-licensed attorney.**
> Section 4 states a legal duty that applies to every volunteer personally.

The Organization brings together people of many cultures, faiths and
backgrounds. That is the work, not a side effect of it. This code exists so that
everyone who walks into a PAWTX event knows what to expect from the people
running it.

---

## 1. Respect

- Treat participants, families, other volunteers and staff with courtesy,
  whatever their race, national origin, religion, language, immigration status,
  sex, sexual orientation, gender identity, age, disability or politics.
- Do not proselytise. Volunteers do not use PAWTX activities to promote a
  religious or political position, or to recruit for any group.
- Ask before you assume. People's names, pronouns, dietary needs and customs are
  theirs to tell you.
- Harassment of any kind — verbal, physical, sexual, or online — ends a
  volunteer's involvement.

## 2. Safety

- Follow your supervisor's safety instructions, and stop and ask if something
  looks unsafe.
- Report every accident, injury, near-miss and instance of property damage to
  your supervisor **the same day**, even where nobody was hurt.
- Do not lift beyond what you can manage safely. Ask for help.
- Outdoor events in West Texas get dangerously hot. Drink water, use shade, and
  tell someone if you or anyone else shows signs of heat illness.
- Do not volunteer while impaired by alcohol or drugs.

## 3. Working with children and vulnerable adults

These are not suggestions. They are the conditions of working with minors.

- **Stay in sight.** Do not be alone with a child who is not your own where you
  cannot be observed. Two adults, or a place others can see, always.
- **No private contact.** Do not contact a minor participant privately by phone,
  text, social media or messaging app. Communication goes through the
  Organization or the parent.
- **No transport alone**, and none at all without written parental
  authorisation.
- **No photographs on personal devices**, and none published anywhere without
  the consent recorded under `04-media-consent.md`.
- **No physical discipline**, and no physical contact beyond what is ordinary,
  brief and in view of others.
- **No gifts** to an individual child outside a programme.

## 4. Reporting suspected abuse — this is the law, and it is personal to you

**Texas Family Code §261.101 requires any person who suspects that a child has
been abused or neglected to report it within 48 hours. This duty is yours
personally. It cannot be satisfied by telling a supervisor and leaving it
there, and it is not limited to professionals.**

- Texas Abuse Hotline: **1-800-252-5400**, or <https://www.txabusehotline.org>.
- Where a child is in immediate danger, call **911** first.
- Also tell the Organization's designated contact so it can act — but **the
  report to the state is yours to make**, and telling the Organization does not
  discharge it.
- Do not investigate. Do not interview the child. Do not confront the person
  suspected. Write down what you saw and heard, in the words used, as soon as
  you can.
- Failing to report is a criminal offence in Texas.

## 5. Confidentiality

What you learn about a participant, a family receiving assistance, a donor or
another volunteer stays inside the Organization. Do not repeat it, and do not
post about it. This continues after you stop volunteering. Where you are unsure,
treat it as confidential and ask.

## 6. Representing the Organization

- Do not speak to the press on the Organization's behalf. Refer enquiries to
  staff.
- Do not post on social media as though you speak for PAWTX. Sharing what you
  did as a volunteer is welcome; speaking for the Organization is not.
- Do not sign anything, order anything or make a commitment in the
  Organization's name without written authorisation.

## 7. Money and property

- Do not accept cash donations personally. Direct donors to the Organization.
- Use PAWTX property and supplies for PAWTX purposes only.
- Declare any conflict of interest — a family business bidding for work, for
  example — to your supervisor before it becomes a problem.

## 8. If something goes wrong

Raise it with your supervisor. If the concern is about your supervisor, or you
would rather not go to them, write to **paowtx@gmail.com**.

Nobody will be penalised for raising a concern honestly and in good faith. The
Organization will not retaliate against a volunteer for making a report,
including a report under section 4.

## 9. Consequences

Breach of this code may lead to a conversation, to removal from an activity, or
to the end of the volunteer relationship — the response fits what happened.
Conduct that puts a child or vulnerable adult at risk, and harassment, end the
relationship immediately and may be reported to the authorities.$doc$,
  $doc$[Spanish translation pending attorney-reviewed English text. Contact paowtx@gmail.com for this document in Spanish.]$doc$,
  true
from doc
on conflict (document_id, version) do update set
  body_md = excluded.body_md, body_md_es = excluded.body_md_es, is_current = true;

